### ISSUE TITLE
Discover a data source to start working with

### ISSUE THREAD

**Issue by danddore** [danddore/seattle-business-demographics#2]
What data source(s) can be used to help understand and answer questions about the business demographics of the City of Seattle?

**Comment by GavenMartung** [comment]
For general data that the government collects, specifically pertaining to Seattle Business Demographics, One could use https://www.data.gov/.
Within the search bar, Search Seattle Business and you will get numerous results pertaining to your topic over the years.

**Comment by danddore** [comment]
I found [this](https://data.seattle.gov/City-Business/Active-Business-License-Tax-Certificate/wnbq-64tb) dataset on "Active Business License Tax Certificate". It contains active business license tax certificate data from the City of Seattle. This dataset includes information about businesses such as business legal name, trade name, ownership type, naics code, license start date, location, unique license number, and unique business identifier.  

With the information provided in the dataset, we can answer a lot of questions about the demographics of businesses that operate in Seattle.
